### ISSUE TITLE
i2smic.py puts options in wrong file

### ISSUE THREAD

**Issue by edmcdonagh** [adafruit/Raspberry-Pi-Installer-Scripts#124]
Options are being put in `/etc/modules-load.d/snd-i2smic-rpi.conf` which causes `systemd-modules-load.service` to fail.

Mistake was introduced in commit d3c76a3e1aa5

I'll send in a PR to correct it.

**Comment by ladyada** [comment]
thank you :)

**Comment by edmcdonagh** [comment]
No problem - had me going round in circles for a while this afternoon!

**Comment by makermelissa** [comment]
Fixed by #125
