### ISSUE TITLE
Some settings not working with 1.3" TFT

### ISSUE THREAD

**Issue by caternuson** [adafruit/Raspberry-Pi-Installer-Scripts#128]
Re this thread:
https://forums.adafruit.com/viewtopic.php?f=50&t=171623

Recreated with Pi Zero W, `2020-08-20-raspios-buster-armhf-lite.img`, and following Python script process per guide:
https://learn.adafruit.com/adafruit-1-3-color-tft-bonnet-for-raspberry-pi/kernel-module-install

Using guide example:
```
sudo python3 adafruit-pitft.py --display=st7789_240x240 --rotation=180 --install-type=console
```
results in:
![pitft_bonnet_test](https://user-images.githubusercontent.com/8755041/98750519-0c546200-2373-11eb-8d82-54739c01feaf.jpg)

Re-running and selecting 0 degree rotation results in:
![pitft_bonnet_test2](https://user-images.githubusercontent.com/8755041/98750528-11b1ac80-2373-11eb-9036-69ba8b0a3a16.jpg)

**Comment by caternuson** [comment]
Related?
https://forums.adafruit.com/viewtopic.php?f=8&t=170661#p834732

**Comment by ladyada** [comment]
probably a typo - @makermelissa plz look on monday, something just got swapped around?

**Comment by makermelissa** [comment]
Ok, it took forever to update my Pi, but I was able to reproduce as well.

**Comment by makermelissa** [comment]
I'm getting the same issue when running adafruit-pitft.sh and choosing the same options. It could be something changes in the 8/20 release of Raspberry Pi that I missed. I'm going to look a little deeper into this.

**Comment by makermelissa** [comment]
I just updated the guide so it appears the correct direction too. Apparently it is 0 degrees if using the console and 180 if using FBCP.
