### ISSUE TITLE
Mic and speaker work simultaneously?

### ISSUE THREAD

**Issue by hyansuper** [adafruit/Raspberry-Pi-Installer-Scripts#132]
Hi, Adafruit team
thank you for the many tutorial about RPi !

My RPi zero connects a [i2s mic](https://learn.adafruit.com/adafruit-i2s-mems-microphone-breakout/raspberry-pi-wiring-and-test) and a [MAX98357 speaker borad](https://learn.adafruit.com/adafruit-max98357-i2s-class-d-mono-amp/raspberry-pi-usage#create-asound-dot-conf-file-5-28).
I followed your tutorials about these two devices and now I can record and playback sound.

So, I am trying to push the limit a little bit, by experimenting with [this code from sounddevice example](https://python-sounddevice.readthedocs.io/en/0.4.1/examples.html#input-to-output-pass-through) that record and playback sound simultaneously. and obviously the code failed since i2s mic and speaker both share pin 18 and 19 on RPi.

My question is, can we use other pins than 18/ 19, and make another i2s bus on RPi ?

**Comment by ladyada** [comment]
i2s pins are fixed and cannot be changed, for raspi i2s help you may want to post in the raspi forums. github issues are not where tech support is done
