### ISSUE TITLE
Update URL for wget in converted_shell_scripts

### ISSUE THREAD

**Issue by figital** [adafruit/Raspberry-Pi-Installer-Scripts#145]
on this page ... (in this file)

https://github.com/adafruit/Raspberry-Pi-Installer-Scripts/blob/master/converted_shell_scripts/adafruit-pitft.sh

change the wget URL to this

https://raw.githubusercontent.com/adafruit/Raspberry-Pi-Installer-Scripts/master/converted_shell_scripts/adafruit-pitft.sh

(otherwise the wget command throws a 404)

**Comment by makermelissa** [comment]
Hi, we changed over to using python scripts recently. Is there a reason you are still trying to use the old shell script?

**Comment by figital** [comment]
oops sorry about that didn't notice the py script. will close. (and try the  python version)

just can't get rid of an spidev0.0 not found error :p (trying to run the miniPiTFT)
