### ISSUE TITLE
Unable to locate package python-spidev

### ISSUE THREAD

**Issue by NitroProp** [adafruit/Raspberry-Pi-Installer-Scripts#156]
Hello, I'm installing the oled software support following the adafruit leraning page for the adafruit 1.3" color tft bonnet. Everything worked as it should until i executed: sudo python3 adafruit-pitft.py --display=st7789_240x240 --rotation=0 --install-type=console
It appears that apt is unable to find python-spidev and the script stop. Already installed python3-dev but ... this script is not working on my piZeroW. the raspbian release the latest (downloaded today)

**Comment by makermelissa** [comment]
Oh yeah, I just updated the script about an hour ago and it includes a change to use python3-spidev instead. Please try again.
