### ISSUE TITLE
Add Kernel version detection to Raspberry Pi Blinka Script

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Raspberry-Pi-Installer-Scripts#162]
I keep running into this when I set up a new Pi in that I run the Raspi-blinka script after updating, but before rebooting and the new kernel hasn't been updated, so there's a modprobe error message and I run it again after rebooting just to be safe. It would be nice to check if the kernel has been updated, but a reboot hasn't occurred. It should be as simple as checking the loaded kernel (`uname -r`) against available folders inside the `/lib/modules` folder and requesting a reboot first if it's not there.

**Comment by ladyada** [comment]
add it to the shell helper library!
