### ISSUE TITLE
Have Blinka inform user of minimum Python version during install

### ISSUE THREAD

**Issue by TinManAkshay** [adafruit/Raspberry-Pi-Installer-Scripts#169]
Hi,

I am installing this library right now and I am getting this error shown below:

pi@raspberrypi:~ $ sudo pip3 install Adafruit_Blinka
Collecting Adafruit_Blinka
  Using cached https://www.piwheels.org/simple/adafruit-blinka/Adafruit_Blinka-5.13.1-py3-none-any.whl
Collecting Adafruit-PureIO>=1.1.7 (from Adafruit_Blinka)
  Using cached https://www.piwheels.org/simple/adafruit-pureio/Adafruit_PureIO-1.1.8-py3-none-any.whl
Requirement already satisfied: RPi.GPIO in /usr/lib/python3/dist-packages (from Adafruit_Blinka)
Collecting sysv-ipc (from Adafruit_Blinka)
  Using cached https://files.pythonhosted.org/packages/0c/d7/5d2f861155e9749f981e6c58f2a482d3ab458bf8c35ae24d4b4d5899ebf9/sysv_ipc-1.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-pysgk14t/sysv-ipc/setup.py", line 11, in <module>
        import prober
      File "/tmp/pip-build-pysgk14t/sysv-ipc/prober.py", line 137
        d["SYSV_IPC_VERSION"] = f'"{version}"'
                                             ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-pysgk14t/sysv-ipc/

**Comment by makermelissa** [comment]
There doesn't seem to be much in the way of having Blinka inform the user, but we can definitely add the check to the Blinka installer script, so I transferred the issue.
