### ISSUE TITLE
Homogenize script permissions

### ISSUE THREAD

**Issue by mamoit** [adafruit/Raspberry-Pi-Installer-Scripts#17]
```
-rwxrwxr-x adafruit-pitft.sh
-rwxrwxr-x arcade-bonnet.sh
-rw-rw-r-- i2c.sh
-rw-rw-r-- i2samp.sh
-rwxrwxr-x joy-bonnet.sh
-rw-rw-r-- pi-eyes.sh
-rwxrwxr-x pitft-fbcp.sh
-rwxrwxr-x pi-touch-cam.sh
-rw-rw-r-- README.md
-rw-rw-r-- read-only-fs.sh
-rwxrwxr-x retrogame.sh
-rw-rw-r-- rgb-matrix.sh
-rw-rw-r-- rtc.sh
```
Some scripts are executable, others aren't.
I can solve this, just asking if it is intended for some reason.

**Comment by ladyada** [comment]
no reason for it, we write the scripts on Windows anyhow & we expect people to +x on run!

**Comment by mamoit** [comment]
I disagree, since for someone who is new to linux and is following instructions from somewhere and just wants to clone the repo and run a script, not having the right permissions (since they will be most probably be cloning on a rpi) can introduce frustration.
This is not a RFC and more of a 'let me know and I'll do it for you'.

**Comment by ladyada** [comment]
okdoke if you can submit a PR we can look at it!

**Comment by mamoit** [comment]
There you go.

**Comment by ladyada** [comment]
yaaaaay!
