### ISSUE TITLE
Can't install i2s mic on Pizero

### ISSUE THREAD

**Issue by gavspav** [adafruit/Raspberry-Pi-Installer-Scripts#171]
When running the install script I'm getting some errors:

make[1]: *** /lib/modules/4.19.71-rt24+/build: No such file or directory.  Stop.
make: *** [Makefile:38: clean] Error 2

make -C /lib/modules/4.19.71-rt24+/build M=/home/patch/Raspberry-Pi-Installer-Scripts/i2s_mic_module clean
make[1]: *** /lib/modules/4.19.71-rt24+/build: No such file or directory.  Stop.
make: *** [Makefile:35: all] Error 2

make -C /lib/modules/4.19.71-rt24+/build M=/home/patch/Raspberry-Pi-Installer-Scripts/i2s_mic_module modules
make: *** No rule to make target 'snd-i2smic-rpi.ko', needed by 'install'.  Stop.

**Comment by makermelissa** [comment]
What version of Raspberry Pi OS are you running?

**Comment by paulhobbel** [comment]
I am facing the same issue, running latest version of Raspberry OS

**Comment by paulhobbel** [comment]
I solved it by running
```
sudo apt-get install --reinstall raspberrypi-bootloader raspberrypi-kernel
```

**Comment by makermelissa** [comment]
Great solution @paulhobbel and thanks for sharing what worked.
