### ISSUE TITLE
adafruit-pitft.sh SSL issues

### ISSUE THREAD

**Issue by smooreace** [adafruit/Raspberry-Pi-Installer-Scripts#173]
When running the above, after asking for screen type and rotation I get the following block of failures

`Reading package lists...
.........
[PITFT] Installing Python libraries & Software...
Installing Pre-requisite Software...This may take a few minutes!
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(185090184, u'[X509] no certificate or crl found (_ssl.c:3063)'),)': /simple/evdev/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(185090184, u'[X509] no certificate or crl found (_ssl.c:3063)'),)': /simple/evdev/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(185090184, u'[X509] no certificate or crl found (_ssl.c:3063)'),)': /simple/evdev/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(185090184, u'[X509] no certificate or crl found (_ssl.c:3063)'),)': /simple/evdev/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(185090184, u'[X509] no certificate or crl found (_ssl.c:3063)'),)': /simple/evdev/
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(185090184, u'[X509] no certificate or crl found (_ssl.c:3063)'),)': /simple/evdev/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(185090184, u'[X509] no certificate or crl found (_ssl.c:3063)'),)': /simple/evdev/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(185090184, u'[X509] no certificate or crl found (_ssl.c:3063)'),)': /simple/evdev/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(185090184, u'[X509] no certificate or crl found (_ssl.c:3063)'),)': /simple/evdev/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(185090184, u'[X509] no certificate or crl found (_ssl.c:3063)'),)': /simple/evdev/
  Could not find a version that satisfies the requirement evdev (from versions: )
No matching distribution found for evdev
WARNING : Pip failed to install software!`

**Comment by ladyada** [comment]
this is internet connectivity or package issues, does not have anything to do with the software
try it again in a few days and check your internet.
