### ISSUE TITLE
adafruit-pitft.sh doesn't recognize when a mirror is in sources.list (minor)

### ISSUE THREAD

**Issue by samm81** [adafruit/Raspberry-Pi-Installer-Scripts#19]
This is a very minor issue.
I was using an alternate mirror for my raspbian sources (http://mirror.umd.edu/raspbian/raspbian), and the script gave me an error message and quit, telling me to add the official raspbian sources ("mirrordirector.raspbian.org"), even though the mirror sources are also fine.
This is a very minor bug and is probably not worth fixing.
For the record, I just temporarily re-added the official sources to run the script.

**Comment by ladyada** [comment]
i just removed the check, we dont use non-standard sources. if ya do - you're probably capable enough to edit the shell script
