### ISSUE TITLE
"Pip failed to install software!"

### ISSUE THREAD

**Issue by samm81** [adafruit/Raspberry-Pi-Installer-Scripts#20]
When I was using the installer, I got the "Pip failed to install software!" warning.
When inspected the script and tried to manually `pip install evdev`, I received the error "Cannot fetch index base URL http://pypi.python.org/simple/".
This was solved by running `sudo pip install -i https://pypi.python.org/simple/ --upgrade pip`, and then rerunning the script, as per https://stackoverflow.com/questions/21294997/pip-connection-failure-cannot-fetch-index-base-url-http-pypi-python-org-simpl .

**Comment by ladyada** [comment]
should be resolved now with 
https://github.com/adafruit/Raspberry-Pi-Installer-Scripts/commit/be3e0fba5d8d486f0b801fc3bc97b25b89c57f72
