### ISSUE TITLE
installer fails if 'python' alias doesn't exist

### ISSUE THREAD

**Issue by jvosk** [adafruit/Raspberry-Pi-Installer-Scripts#206]
In the `default_python_version` fn def, the line `version = shell.run_command("python -c 'import platform...'" ...)` fails silently if the `python` alias doesn't exist.  The `.run_command` gives `/bin/sh: 1: python: not found`, and the exit code is `False` instead of `True`, but the script as-is ignore this failure.

Error output below:
```
This script configures your
Raspberry Pi and installs Blinka

RASPBERRY_PI_2B detected.

Traceback (most recent call last):
  File "/home/pi/raspi-blinka.py", line 120, in <module>
    main()
  File "/home/pi/raspi-blinka.py", line 98, in main
    if default_python_version() < 3:
  File "/home/pi/raspi-blinka.py", line 20, in default_python_version
    return float(version[0:version.rfind(".")])
ValueError: could not convert string to float: ''
```

This is on a fresh install of Raspbian on a Pi 2B, output of `cat /etc/os-release` below:
```
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

I made no explicit attempt to uninstall `python2` or remove any aliases of `python` after installation.  Simply ran
```
apt-get update
apt-get upgrade
python3 raspi-blinka.py
```
(with appropriate application of `sudo` as needed).

**Comment by makermelissa** [comment]
Hmm, interesting. The purpose was to see which version running `python` yielded, but I hadn't accounted to a missing alias call.
