### ISSUE TITLE
module name

### ISSUE THREAD

**Issue by Haotian-Shi-cyber** [adafruit/Raspberry-Pi-Installer-Scripts#208]
is it snd-i2smic-rpi or snd-i2s-rpi?
mine shows snd-i2smic-rpi, just want to make sure it is right module, thanks

**Comment by makermelissa** [comment]
I'm not sure what you're referring to. In https://github.com/adafruit/Raspberry-Pi-Installer-Scripts/blob/main/i2smic.py#L45-L52 it has snd-i2smic-rpi. Where did you see `snd-i2s-rpi`?

**Comment by Haotian-Shi-cyber** [comment]
problem solved, it was another one I installed that caused driver crash, I uninstalled it and it works now, thanks very much
