### ISSUE TITLE
Does not work for OSMC

### ISSUE THREAD

**Issue by blixten85** [adafruit/Raspberry-Pi-Installer-Scripts#227]
Raspberry pi 4B
OSMC x64

**Comment by ladyada** [comment]
its not guaranteed to work on OSMC but you'll get more help if you include details, error messages, screenshots, etc

**Comment by blixten85** [comment]
![Screenshot_20220802-172109_JuiceSSH](https://user-images.githubusercontent.com/36226327/182411343-98c5dced-9d5c-4059-8702-3187f1fbc1a4.png)

**Comment by makermelissa** [comment]
What are you running this on? Here's where it displays the error message: https://github.com/adafruit/Raspberry-Pi-Installer-Scripts/blob/main/i2samp.sh#L268-L272.

**Comment by makermelissa** [comment]
Just after I asked, I realized the issue it's not working is because I don't think it's been tested on a 64-bit OS. It probably just needs some updating now that Raspberry Pi OS has an official 64-bit version.

**Comment by blixten85** [comment]
Maybe.

It's OSMC on a raspberry pi 4B. Arm64
