### ISSUE TITLE
How to change bit depth to 16 of I2S MEMS Microphone ?

### ISSUE THREAD

**Issue by superuser789** [adafruit/Raspberry-Pi-Installer-Scripts#230]
I have successfully setup adafruit I2S mem microphone on my RPi3 running buster by following guide [here](https://learn.adafruit.com/adafruit-i2s-mems-microphone-breakout/raspberry-pi-wiring-test). 

It records audio well using arecord :
`arecord -D 'plughw:2,0' -c1 -r 48000 -f S32_LE -t wav -V mono -v file.wav`

But I need 16-bit signed PCM audio for my project.
Running  `arecord -D 'plughw:2,0' -c1 -r 48000 -f S16_LE -t wav -V mono -v file.wav`  does not record anything.

What changes do I need to make to change bit depth to 16 ?

Thanks.

**Comment by makermelissa** [comment]
Hi, this area is for script bugs. it sounds like the installer script is functioning correctly. If you need further assistance, you can either post something over on the [support forums](https://forums.adafruit.com) or in our [discord chat](http://adafru.it/discord).

That being said, you may be able to check if the S16_LE format is supported by the device with the command `arecord --dump-hw-params`. If not, perhaps you could try using some kind of format converter.
