### ISSUE TITLE
2.8" 320x240 TFT display: can it be used with Pico?

### ISSUE THREAD

**Issue by ExperiMentor** [adafruit/Raspberry-Pi-Installer-Scripts#238]
Would it be possible to use the "2.8" 320x240 TFT w/Touch Screen for Raspberry Pi" display with a Pico? 
For my present project it would be OK if just display (without touch).
Has that been tried, any examples?
Or is it not possible eg if it needs 5v power?

**Comment by makermelissa** [comment]
Theoretically it's possible. However, you would probably have an easier time wiring up a 2.8" breakout. I think the VBUS pin allows you to get 5v from the USB. You can check out the schematic here: https://learn.adafruit.com/adafruit-pitft-28-inch-resistive-touchscreen-display-raspberry-pi/downloads.
