### ISSUE TITLE
3.5" TFT screen works on RaspberryPi 3B+ but not Pi Zero W

### ISSUE THREAD

**Issue by cajuncoder** [adafruit/Raspberry-Pi-Installer-Scripts#239]
### Script Command

```shell
sudo python3 adafruit-pitft.py --display=35r --rotation=90 --install-type=fbcp
```

### Operating System

32bit? Raspberry PiOS with Bullseye

### Hardware

Raspberry Pi Zero W

### Behavior

The Pi Zero W boots up with a white screen, which turns black (backlight still on) when the pi boots into the desktop. The TFT screen is light up, but just displaying a blank black screen. The resistive touch seems to work, but not the display.

This same Pi Zero W and screen worked on a very old Jessie preinstalled image that you guys used to provide. My current install and the same screen also work just fine on the full sized Pi 3B+ that I have. Therefore, I surmise that it must be something wrong with the script.

EDIT:
I've tried now with the 2.8" TFT, and it also doesn't appear to work with the PiZero, but works no problem with the P3B+.
I've tried multiple fresh installs at this point, and can confirm that there's nothing wrong with my hardware (screens, pi zero).

**Comment by makermelissa** [comment]
Tested the 3.5" PiTFT on the Pi Zero W and Pi Zero 2 W and both work without issue. You may want to check the soldering on your 40 pin header on your Pi Zero W.
