### ISSUE TITLE
rotation vs rotate

### ISSUE THREAD

**Issue by mikeysklar** [adafruit/Raspberry-Pi-Installer-Scripts#241]
### Script Command

```shell
sudo script python3 adafruit-pitft.py --display=st7789_240x135 --rotation=270 --install-type=console
```

### Operating System

32-bit Buster Lite

### Hardware

Pi 4B

### Behavior

rotate works with the 1.14” Mini PiTFT in the /boot/config.txt, but rotation does not. 

### Description

A patch was added in November to the adafruit-pitft.py installer to use the word rotation. 

https://github.com/adafruit/Raspberry-Pi-Installer-Scripts/pull/233/files/2f8e05b9fc61a2f4be25d3579de02c02617bec99

This was probably a change compatible with newer kernels that Bullseye uses, but is not compatible with Buster. 

### Additional information

Adafruit Forum thread: https://forums.adafruit.com/viewtopic.php?p=960864

_No response_

**Comment by makermelissa** [comment]
I think this may be a case of updating the documentation as I believe the patch is correct.

**Comment by mikeysklar** [comment]
A forum user had made their setup work after swapping out s/rotation/rotate in their config.txt. I've ordered a 1.14 PiTFT and will verify.

https://forums.adafruit.com/viewtopic.php?t=198749

**Comment by makermelissa** [comment]
Thanks. I meant it's likely the guide itself probably needs to just be changed to have the user use `rotate` instead of `rotation`. I'm just not sure if that's for all boards or just this one.

**Comment by mikeysklar** [comment]
I see. Yes, it might be more appropriate to just change the guide. I'll try some combinations on the displays I have to confirm behavior.

**Comment by makermelissa** [comment]
I started to change the guide, but then realized that was the parameter for the script and not for config.txt. I ended up changing it in the install script.
