### ISSUE TITLE
PiTFT 2.8" Capacitive Touch Inversion Issue

### ISSUE THREAD

**Issue by CaptainZ1** [adafruit/Raspberry-Pi-Installer-Scripts#248]
### Script Command

```shell
sudo python3 adafruit-pitft.py --display=28c --rotation=0 --install-type=console
```

### Operating System

64-bit Raspberry Pi OS Desktop (2023-02-21)

### Hardware

Raspberry Pi 3 Model B V1.2

### Behavior

The script installs as expected, but touch events are inverted in the x and y axes, making the touchscreen unusable. 

i.e. you move up, it goes down. you move left, it goes right

### Additional information

I **was able to fix this issue** by setting the touch-invx and touch-invy equal to false in my /boot/config.txt file. This is an easy enough fix for those in need of a solution now, but this is still unexpected behavior.

Looking at the current code for the installer, I believe this issue may be related to lines 78-86 of the adafruit-pitft.py script. I believe the rotation angle does not match with the string input, i.e. 0 should be 0, not 90 while 180 should be 180, not 90?

`        
"overlay": """dtoverlay=pitft28-capacitive,speed=64000000,fps=30
dtoverlay=pitft28-capacitive,{rotation}""",
        "calibrations": "320 65536 0 -65536 0 15728640 65536",
        "rotations": {
            "0": "rotate=90,touch-invx=true,touch-invy=true",
            "90": "rotate=90,touch-swapxy=true,touch-invx=true",
            "180": "rotate=90",
            "270": "rotate=270,touch-swapxy=true,touch-invy=true",
        },
`

**Comment by makermelissa** [comment]
It used to be that we had to specify the touch parameters, but it appears they fixed it in the OS so we don't. I'm currently updating the script so it just uses the defaults.
