### ISSUE TITLE
adafruit-pitft.sh Sources check fails on newest Raspbian

### ISSUE THREAD

**Issue by JenusL** [adafruit/Raspberry-Pi-Installer-Scripts#25]
Raspberry Pi changed the default mirror from mirrordirector.raspbian.org to raspbian.raspberrypi.org making the script fail on all new installs.  
Here's the commit with some comments as well: https://github.com/RPi-Distro/raspberrypi-sys-mods/commit/12b51a608379fe4edec2b3e9c793c214d0960f17

I suggest a change of the check function to also take the new location. KLine 145:</br>
`    if [[ $(grep -h ^deb /etc/apt/sources.list /etc/apt/sources.list.d/* | grep "mirrordirector.raspbian.org\|raspbian.raspberrypi.org") ]]; then`

But seeing that others have issues with their own sources as well (see #19), maybe this whole source check should be rethinked completely or just skipped.

**Comment by ladyada** [comment]
i just removed it, we dont use non-standard sources. if ya do - you're probably capable enough to edit the shell script
