### ISSUE TITLE
I2S Mic may be out of date on Raspberry Pi OS Bookworm

### ISSUE THREAD

**Issue by Bradams2212** [adafruit/Raspberry-Pi-Installer-Scripts#274]
Been trying to setup a pair of MEMS mics on my Raspberry Pi 400 using tutorials that make use of your setup script. Although it worked in the past, trying now it will run fine but does not show up as a recording device. I've asked around and they say its probably just out of date for current raspbian. If this could be updated to current or an alternative method given, that would be greatly appreciated.

**Comment by makermelissa** [comment]
It looks like Bookworm made some changes and removed some sysfs stuff, which broke the i2smic stuff.

**Comment by LostNulide** [comment]
I found out, that the i2s device is disabled by default in Bookworm. If you enable it in `/boot/firmware/config.` with the following line
`dtparam=i2s=on`
it should work again. At least it does on my system Raspberry Pi 4 with the latest Bookworm.
