### ISSUE TITLE
Externally managed environment error when installing python prerequisites

### ISSUE THREAD

**Issue by nightduck** [adafruit/Raspberry-Pi-Installer-Scripts#286]
### Script Command

```shell
sudo pip install --upgrade adafruit-python-shell
```

### Operating System

64-bit Raspberry Pi OS

### Hardware

Raspberry Pi 3B

### Behavior

When installing the prerequisites for i2smic.py on a fresh OS install, I get a complaint that prevents me from using pip

### Additional information

Packages can be forcibly installed with the --break-system-packages flag

**Comment by makermelissa** [comment]
This sounds like you are running on Bookworm, which requires a virtual environment. However, i2smic is not currently working on bookworm. See #274.

Closing this since I added a warning to the guide. Guide will be updated with venv instructions once it is functioning on bookworm.
