### ISSUE TITLE
i2samp.sh introduced invalid characters in config.txt

### ISSUE THREAD

**Issue by KevinOlive** [adafruit/Raspberry-Pi-Installer-Scripts#3]
After running the i2samp.sh script, powering down the pi0w and attaching the stereo bonnet, my pi would not boot. No lights, nothing; however, the keyboard lights did light at power up. I thought I had messed up the soldering and somehow fried my pi. I really thought it was dead. Then on a whim, I loaded the SD card on my Mac and looked at /boot/config.txt. There were invalid chars (displayed as upside down "?") in the file at the end after # NOOBS Auto-generated Settings. I apologize that I didn't make a backup of the file.
Anyway, I removed those chars and the pi booted without a problem and the speaker bonnet is tested okay.

**Comment by ladyada** [comment]
closed - not able to reproduce!
