### ISSUE TITLE
PiTFT 3.5" Plus slow touch response

### ISSUE THREAD

**Issue by mikeysklar** [adafruit/Raspberry-Pi-Installer-Scripts#307]
### Script Command

```shell
sudo -E env PATH=$PATH python3 adafruit-pitft.py --display=35r --rotation=90 --install-type=mirror
```

### Operating System

64-bit Pi OS Bookworm Desktop

### Hardware

Pi 4B

### Behavior

2min delay with touch screen updates

### Description

Install runs smoothly. X comes up. Touch response works. There is a two minute lag from when I press a location on the screen to when it responds.

### Additional information

![IMG_2598](https://github.com/adafruit/Raspberry-Pi-Installer-Scripts/assets/1987700/98a5ff83-f20e-4d7d-b62f-b3ea6ea3a13b)

evtest runs fine with immediate output.

dmesg might provide a clue here:

```text
$ dmesg | grep -i stmpe
[    2.221584] stmpe-spi spi0.1: stmpe610 detected, chip id: 0x811
[    2.244321] stmpe-gpio stmpe-gpio: DMA mask not set
[    6.148211] stmpe-ts stmpe-ts: DMA mask not set
[    6.461093] input: stmpe-ts as /devices/platform/soc/fe204000.spi/spi_master/spi0/spi0.1/stmpe-ts/input/input4
```

Based on [forum issue brought up by @ronaldlw](https://forums.adafruit.com/viewtopic.php?t=210294).

**Comment by mikeysklar** [comment]
Rolled back to Bullseye Legacy 64-bit Full install and touchscreen is very responsive and usable. No issues on that legacy release. 

![Uploading Screenshot 2024-04-26 at 10.25.19 AM.png…]()

**Comment by makermelissa** [comment]
Good to know. In both cases, it is using the touch drivers provided by Raspberry Pi. It's possible they need to be updated and a PR submitted to Raspberry Pi.

**Comment by mikeysklar** [comment]
@makermelissa -

I suspect the touch driver STMPE is good as evtest is responsive. 

Somewhere along the Xwin process of translating those coordinates to icons to opening stuff a timeout must be happening. I'm looking through the log files and see another clue.

pi5 : Bookworm 12/5/23 : $HOME/.xsession

```text
II 26-04-24 12:31:01.035 - [src/view/xdg-shell.cpp:25] New xdg popup
II 26-04-24 12:31:23.363 - [src/view/xdg-shell.cpp:25] New xdg popup
EE 26-04-24 12:31:24.719 - [types/seat/wlr_seat_touch.c:303] got touch point focus for unknown touch point
```

I'm suspicious of WAYLAND and xdg interactions.

**Comment by mikeysklar** [comment]
Yeah...Wayland it is...

raspi-config --> Advanced --> W1 X11 (do not use Wayfire Wayland backend)

modify **/boot/firmware/config.txt** comment out this line:
```text
#dtoverlay=vc4-kms-v3d
```

reboot...

Display has instant response time on Pi5 Bookworm / 12/5/23 release.

**Comment by mikeysklar** [comment]
@ronaldw's automated change for rolling back to the Xorg server.

```
sudo sed -e '/dtoverlay=vc4/ s/^#*/#/' -i /boot/firmware/config.txt
sudo sed -i -e '/greeter-session=/ s/=.*/=pi-greeter/' /etc/lightdm/lightdm.conf
sudo sed -i -e '/user-session=/ s/=.*/=LXDE-pi-x/' /etc/lightdm/lightdm.conf
sudo sed -i -e '/autologin-session=/ s/=.*/=LXDE-pi-x/' /etc/lightdm/lightdm.conf
```

**Comment by makermelissa** [comment]
Thanks. I'm working on updating the script to temporarily switch to x11 (which should provide a temporary workaround) until we can get it working in Wayland again.

**Comment by makermelissa** [comment]
I'm pretty sure the 2.8" resistive touch screen (with STMPE610) uses the same driver, so will test that out as well.

**Comment by makermelissa** [comment]
To automatically change to X11, you can run `sudo raspi-config nonint do_wayland W1`, which runs the raspi-config script that runs the sed commands.

**Comment by makermelissa** [comment]
#309 should fix the issue.

**Comment by mikeysklar** [comment]
Confirmed.

Pi5 / Bookworm latest drop + updates works smooth with X11 rollback updates added to adafruit-pitft.py today.

**Comment by mikeysklar** [comment]
Pi4 / Bookworm 3/14 drop + PiTFT 3.5" Plus

Also works smoothly with adafruit-pitft.py.

Two notable differences:

1) resolution:
* Pi5 - 480x320 
* Pi4 - 720x480 (without mouse pointer)

2) mouse pointer
* Pi5 no mouse pointer, just touchpad style 
* Pi4 mouse pointer, works better with a toothpick for selection than a finger

**Comment by mikeysklar** [comment]
Should the file /boot/firmware/config.txt contain the correct resolution for this display?

change this:

```
hdmi_cvt=720 480 60 1 0 0 0
```

to this:

```
hdmi_cvt=480 320 60 1 0 0 0
```

**Comment by makermelissa** [comment]
I believe the reason the resolutions are different was because it wasn't being scaled in the config.txt anymore when it was updated for wayland, which ignores those parameters and the changes are performed in the wayfire.ini file instead. However, for non-wayland devices, it should be the 720x480 because the start menu can become inaccessible otherwise due to screen height.

**Comment by mikeysklar** [comment]
kk. You can close this issue.
