### ISSUE TITLE
License of scripts

### ISSUE THREAD

**Issue by ericschultz** [adafruit/Raspberry-Pi-Installer-Scripts#49]
First off, thanks for the awesome scripts.

I was wondering what license the scripts in the repository are under. I didn't see any license in the README or the scripts themselves but I only looked at the one I was interested in :)

**Comment by ladyada** [comment]
which one

**Comment by ericschultz** [comment]
This was the one I was looking at: https://github.com/adafruit/Raspberry-Pi-Installer-Scripts/blob/master/adafruit-pitft.sh

**Comment by ladyada** [comment]
ok done!
