### ISSUE TITLE
read-only-fs and PIXEL

### ISSUE THREAD

**Issue by Miky94** [adafruit/Raspberry-Pi-Installer-Scripts#52]
Hi,
I'm trying the **read-only-fs.sh** script on a **Pi Zero W** with **2019-04-08-raspbian-stretch-lite** installing the GPIO-halt utility, but I installed **PIXEL** with
`sudo apt install raspberrypi-ui-mods`
and I read [here](https://learn.adafruit.com/read-only-raspberry-pi?view=all) it is not supported so can I just switch to CLI with:
```
sudo raspi-config
Boot Options
Destkop / CLI
Console Autologin
```
or do I need to uninstall it and how ?
on Raspbian there's only a script that save pictures on a USB stick using python-picamera
Thanks

**Comment by ladyada** [comment]
it almost certainly impossible to have both togehter and we dont have info on how to uninstall. please start with a fresh copy of raspbian lite :)
