### ISSUE TITLE
adafruit-pitft.sh: Support for RPi4 running Buster

### ISSUE THREAD

**Issue by docbobo** [adafruit/Raspberry-Pi-Installer-Scripts#55]
Easy install script doesn't work with the latest Raspbian that's required to run on RPi 4.

**Comment by ladyada** [comment]
thanx, not surprising :) do you want to try submitting a PR?

**Comment by makermelissa** [comment]
When running the installer script, I get the following:
```
Installing Pre-requisite Software...This may take a few minutes!
E: Unable to locate package tslib
WARNING : Apt failed to install software!
```

I'll look into this further.

**Comment by ladyada** [comment]
https://github.com/adafruit/Raspberry-Pi-Installer-Scripts/issues/46

**Comment by makermelissa** [comment]
Thanks!
