### ISSUE TITLE
During shutdown of RP3 display is frozen

### ISSUE THREAD

**Issue by varosi** [adafruit/Raspberry-Pi-Installer-Scripts#61]
When I do Shutdown of RP3 - 2.8 Capacitive Touch display freeze. 
I expect at least it to turn off to black during Shutdown process or at best close to the end of the process.

**Comment by ladyada** [comment]
that's normal, the backlight is on by default!

**Comment by varosi** [comment]
It’s not about the backlight, it’s about the image displayed on the display. Image is just frozen. It would be nice if instead of that a black blank image is visualized before shutdown. Is it possible?

**Comment by ladyada** [comment]
hmm you'd have to write something that, on shutdown, draws an image using `fbi` - see if there's some guide on making a systemd on-shutdown command-runner :)
