### ISSUE TITLE
Mirror console to HDMI?

### ISSUE THREAD

**Issue by init99** [adafruit/Raspberry-Pi-Installer-Scripts#68]
Re: adafruit-pitft.sh

After setting up a 1.14" display I noticed the console isn't sent to HDMI anymore. I then reran the script to set up a 1.3" display instead, rebooted, and lost display on any PiTFT display... I now need to troubleshoot without any console access.

Is there any way to mirror the console to the HDMI port?

**Comment by ladyada** [comment]
you can setup 'mirror from HDMI' and then put console on HDMI, but it wont work very we

you can ssh in or, go to /boot/config.txt and remove the pitft stuff at the bottom. if you have more Q's please post in the forum :)
