### ISSUE TITLE
CMAKE argument deprecated in Pitft.sh

### ISSUE THREAD

**Issue by ankonaskiff17** [adafruit/Raspberry-Pi-Installer-Scripts#74]
PITFT.sh
I am new at this but when I run the PiTFT.sh easy install after selecting the screen size and orientation it starts trying to install various libraries but it gets to a step:

 [PITFT] Adding FBCP support...
Installing cmake...
W: --force-yes is deprecated, use one of the options starting with --allow instead.
Downloading rpi-fbcp...
Uncompressing rpi-fbcp...

Something is not right with the script and among other things you can manually create the /dev/input/touchscreen directory and on the reboot that is the final step, it deletes the touchscreen directory. /dev/input remains but touchscreen is removed,

**Comment by ladyada** [comment]
deprecation warning fixed
