### ISSUE TITLE
adafruit-pitft.sh: Installation for ST7789V fails

### ISSUE THREAD

**Issue by galvanized** [adafruit/Raspberry-Pi-Installer-Scripts#77]
I'm trying to use adafruit-pitft.sh to install support for the Adafruit 1.14" 240x135 Color TFT Display (ST7789). However, doing so fails. Software and script are up-to-date today 2020-03-14.

Pi: Raspberry Pi Zero W V1.1
OS: Raspbian 10 (buster)
Display: [Adafruit 1.14" 240x135 Color TFT Display + MicroSD Card Breakout - ST7789](https://www.adafruit.com/product/4383)
Script: adafruit-pitft.sh

***Selections***
Configuration: 6 (MiniPiTFT 1.14" display (240x135) - WARNING! CUTTING EDGE! WILL UPGRADE YOUR KERNEL TO LATEST)
Rotation: 4 (0 degrees (portrait))

***Output excerpts***
`[PITFT] Installing Python libraries & Software...`
`Installing Pre-requisite Software...This may take a few minutes!`
`[PITFT] Updating /boot/config.txt...`
`FATAL ERROR: Couldn't open "overlays/minipitft114-overlay.dts": No such file or directory`

...and after upgrade...
`./adafruit-pitft.sh: line 261: cd: st7789_module: No such file or directory`
`make: Entering directory '/usr/src/linux-headers-4.19.97+'`
`scripts/Makefile.build:45: /home/pi/Makefile: No such file or directory`
`make[1]: *** No rule to make target '/home/pi/Makefile'.  Stop.`
`make: *** [Makefile:1522: _module_/home/pi] Error 2`
`make: Leaving directory '/usr/src/linux-headers-4.19.97+'`
`WARNING : Apt failed to compile ST7789V driver!`

**Comment by ladyada** [comment]
please delete and try re-git-cloneing  the directory, you missed some files :)
https://learn.adafruit.com/adafruit-mini-pitft-135x240-color-tft-add-on-for-raspberry-pi/kernel-module-install
