### ISSUE TITLE
Cap touch change with 2020-02-13 Raspbian

### ISSUE THREAD

**Issue by caternuson** [adafruit/Raspberry-Pi-Installer-Scripts#83]
Re this thread:
https://forums.adafruit.com/viewtopic.php?f=47&t=164446
Verified both the issue and fix in that thread. [PID 2423](https://www.adafruit.com/product/2423) r-touch identifies as `generic ft5x06` with 2020-02-13 Raspbian Lite. Current udev rules setup by installer script don't work.

**Comment by ladyada** [comment]
@caternuson @makermelissa either of y'all want to try fix application?

**Comment by caternuson** [comment]
@ladyada PR'd something simple that seems to work, see #84

**Comment by caternuson** [comment]
Closing. Hopefully fixed by #84.
