### ISSUE TITLE
PiTFT: Uninstall Option

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Raspberry-Pi-Installer-Scripts#85]
In order to make it easier for users to remove the kernel level driver, it would be great to have an uninstall option that went through and cleaned up everything that it installed so users could use it with Python.

**Comment by Trudko** [comment]
@makermelissa Do you please have an idea, what would be workaround till then? I've installed kernel driver but would love to use it with python now.

**Comment by makermelissa** [comment]
Hi. Look in /boot/config.txt. You’ll need to remove the appropriate pitft device tree overlay for now.

**Comment by makermelissa** [comment]
Ok, I had to do this manually on one of my Raspberry Pis today and I had to remove some lines from `/etc/modules` as well.

**Comment by Trudko** [comment]
@makermelissa thank you, could you maybe go more into details what exactly have you changed?

**Comment by makermelissa** [comment]
Fixed via #90

**Comment by makermelissa** [comment]
It's available, so you can look at the script now @Trudko  ;)
