### ISSUE TITLE
PiTFT 3.5" Resistive touch rotation not working

### ISSUE THREAD

**Issue by gazzmanzx6** [adafruit/Raspberry-Pi-Installer-Scripts#87]
With Raspbian Buster the touch rotation in not working when I rotate the screen by 270 degrees.
All touch movement is inverted.
I've tried adding touch-swapxy,touch-invy to the  /boot/config.txt file but it hasn't helped.
Is there anyway to fix this?

**Comment by makermelissa** [comment]
Fixed via #104. Tested in all 4 rotations.

**Comment by gazzmanzx6** [comment]
I now get a completely blank screen after updating. The Pi has started up ok as I can access the desktop via VNC.

**Comment by ladyada** [comment]
after updating, you may need to run the installer script again

**Comment by gazzmanzx6** [comment]
I have run the installer multiple times but always get a blank screen. I’ve even tried uninstalling and reinstalling but no luck.

**Comment by ladyada** [comment]
you can post the output, or try a fresh copy of raspbian - check your wiring and seating as well. we just tested all screens with latest raspi OS

**Comment by gazzmanzx6** [comment]
Ok. Fixed it. Had to update Raspbian and then reinstall PiTFT. All working correctly now. Thanks.

**Comment by makermelissa** [comment]
Excellent

**Comment by gazzmanzx6** [comment]
Thanks for all your work.
