### ISSUE TITLE
Black/gray screen lines with adafruit-pitft.sh

### ISSUE THREAD

**Issue by kokein** [adafruit/Raspberry-Pi-Installer-Scripts#91]
Hello, 

There is something wrong with this new installer. 
I have TFT 2.2" 320×240 (No Touch) thet is no longer able to install with "easy" script. 
I'm getting black/gray lines screen. 
Can You share an old version? It was working about three weeks ago :(

**Comment by kokein** [comment]
Ok i found it working when go back to this version (below) - but "uninsall" did not worked. 
I had to use clean install of distro (raspbian) 
Tested: https://github.com/adafruit/Raspberry-Pi-Installer-Scripts/blob/94f147b64f36721de59f48cbb479eadf876cfafe/adafruit-pitft.sh

**Comment by makermelissa** [comment]
Please provide some more specifics about what options you chose. I just tested with a 2.2" PiTFT with a fresh install on Raspian Full using Screen mirroring and did not experience the symptoms you described. I don't doubt that you are seeing the issues you describe, but I would like to reproduce them so I can figure out where the issue is happening.

Which specific Raspbian image did you experience the issue with?
Is the issue happening with the install, uninstall, or both?
Did you display the console?
Did you choose the screen mirroring option?
Did you reboot after?

Thanks for letting us know.

**Comment by kokein** [comment]
Sure :)
It was Raspbian Lite - clan intsall. (hash checked)
I did use new script as mentioned, but after script finished and reboot
those "stipes" appeared.
It was a actually black screen and some brighter (gray) bars horizontal.
So i did an "uninstall" script. Did not work (noting happen)
Went back to older installer - nothing helped, and did one more time c
clean install (from the same image)
But lunched an older one version (since month ago) and my LCD "woke up" and
now it's working ok.

Which specific Raspbian image did you experience the issue with?
https://www.raspberrypi.org/downloads/raspbian/  *February 2020*
Is the issue happening with the install, uninstall, or both? *both*.
Did you display the console? i'm working on ssh but using lcd as a monotor
console (it was only black/gray bars)
Did you choose the screen mirroring option? ?! 270 degrees rotation option
Did you reboot after?  sure - i've done it several times till tomorrow ,
that was no problems on older scripts.

Nick :)


pon., 18 maj 2020 o 17:48 Melissa LeBlanc-Williams <notifications@github.com>
napisał(a):

**Comment by makermelissa** [comment]
Thanks. I'll give it a try with those options.

**Comment by makermelissa** [comment]
I am still unable to reproduce this. After choosing the install options:
![IMG_1989](https://user-images.githubusercontent.com/2681417/82236574-26901480-98e9-11ea-9265-bd293206a48e.jpeg)
After uninstalling:
![IMG_1990](https://user-images.githubusercontent.com/2681417/82236603-314aa980-98e9-11ea-8eb8-486d79d17cdc.jpeg)

**Comment by kokein** [comment]
I dont know :(

pon., 18 maj 2020 o 18:23 Melissa LeBlanc-Williams <notifications@github.com>
napisał(a):

**Comment by makermelissa** [comment]
Me neither. I'm going to leave this open for now in case anybody else experiences this and we can get more information. Thanks for your help.

**Comment by makermelissa** [comment]
Closing this because I haven't heard anything from anybody else and have been unable to reproduce.
