### ISSUE TITLE
OrangePI R1 install error - libgpiod needs linux headers version >= v5.5.0

### ISSUE THREAD

**Issue by kouliss** [adafruit/Raspberry-Pi-Installer-Scripts#95]
Hello, when installing libgpiod.sh on OrangePI R1 (Armbian Buster, with Linux 5.4.45-sunxi) I am getting an error libgpiod needs linux headers version >= v5.5.0.
Do You have any suggestion what to try to solve this problem?

Thanks

**Comment by makermelissa** [comment]
Hi, I'm not sure if you've already solved this, but there's likely a there's a prebuilt package for armbian. Try installing with the following command:
```
sudo apt-get install libgpiod2 python3-libgpiod gpiod
```

**Comment by makermelissa** [comment]
You can pass either `-l` or `--legacy` if you bump into this error when running the script.
